---
- name: Handler
  hosts: all
  become: yes
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: installed
      notify: Starting
 
  handlers:
    - name: Starting
      service:
        name: httpd
        state: started
...

