---
- name: install jenkins
  hosts: all
  become: yes
  tasks: 
    - name: installs java
      yum: 
        name: java
        state: present

    - name: installs wget
      yum:
        name: wget
        state: present

    - name: downloading jenkins repo
      get_url:
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
        dest: /etc/yum.repos.d/jenkins.repo

    - name: importing key
      rpm_key: 
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: install jenkins
      yum:
        name: jenkins
        state: present

    - name: jenkins start
      service: 
        name: jenkins
        state: started
        enabled: yes
...
