---
- name: Installing tomcat and Java
  hosts: all
  become: yes
  tasks: 
    - name: Installing java
      yum:
        name: java
        state: installed
      
    - name: installing tomcat
      get_url: 
        url: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz"
        dest: /opt

    - name: untar tomcat
      unarchive:
        src: /opt/apache-tomcat-8.5.87.tar.gz
        dest: /opt
        remote_src: yes

    - name: add executable permission
      file:
        path: /opt/apache-tomcat-8.5.87/bin/startup.sh
        mode: 0777

    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.87/bin
...
